### PR TITLE
Extend url template variables with device_id

### PR DESCRIPTION
**Pull request by Fox32**
I mentioned the need for this parameter in the related [MSC 3891 ](https://github.com/matrix-org/matrix-spec-proposals/pull/3819) which implements to device messages. They are relying on the device id to be available, but there is currently no way to access a device id from within a widget (Element Call does this but is cheating :P). Therefore [I propose to include the device id in the available parameters](https://github.com/matrix-org/matrix-spec-proposals/pull/3819#discussion_r1099833846).

### CODE REVIEW

**Comment by Fox32** [comment]
In case this gets merged: It would be helpful to have a new release of the widget-api, so that I can continue the implementation in the matrix-react-sdk.

**Comment by Fox32** [comment]
I would be open to switch from `device_id` to `matrix_device_id` to align with the other names, opinions? There are also parameters without a `matrix_` prefix, but I think it would be a better match here.

**Comment by alunturner** [comment]
Hello, firstly sorry for the delay in getting to this. 

I am really not familiar with this area of the codebase yet so I'll bow to @dbkr 's judgment on this, but commenting to try and get this moving for you.

On the `device_id` vs `matrix_device_id` I think I'd lean towards the former (ie without the `matrix_` prefix) but aware I may be missing some context here. What do you think @dbkr ?

**Comment by Fox32** [comment]
From the security perspective I think it is fine to pass the device id to the widget, especially as the user is asked first before loading an untrusted widget for the first time. The user[ sees the list of potential data](https://github.com/matrix-org/matrix-react-sdk/blob/9a31bef349398915d5e3c0b07cde50e781138da9/src/components/views/elements/AppPermission.tsx) that is shared with the widget and can decide whether he trusts the widget.

**Review by dbkr — COMMENTED** [review]
I think this  seems fine. I also agree that matrix_device_id is probably better to match the other matrix related things rather than client specific settings, so it would probably be good to change that. We should obviously note this on the MSC too.

In terms of security, I think the only concern is widgets now being able to track what device they're used on for each user, although in practical terms they'd likely be able to do this in most cases anyway just with a user agent string or similar. I don't think it's worth having a separate permission for it.

**Review by dbkr — APPROVED** [review]
Thanks!

**Comment by dhenneke** [comment]
@dbkr, @t3chguy would it be possible to get a new release created? Then I could work on https://github.com/matrix-org/matrix-react-sdk/pull/10209 so we get this finished.

**Comment by t3chguy** [comment]
@dhenneke done https://github.com/matrix-org/matrix-widget-api/actions/runs/4893568795

**Comment by dhenneke** [comment]
Thanks

**Pull request merged**
