### PR TITLE
Implement MSC3973: Search users in the user directory with the Widget API

### PR DESCRIPTION
**Pull request by dhenneke**
See https://github.com/matrix-org/matrix-spec-proposals/pull/3973 for more details.

### CODE REVIEW

**Comment by t3chguy** [comment]
Not sure if matrix-widget-api has been made willing to be a playground to implement MSCs upon, deferring to tech lead @andybalaam

**Comment by dhenneke** [comment]
I added more information about the security implications of this change to the linked MSC.

**Comment by andybalaam** [comment]
I missed the notification about this ping, sorry. I'll try to look into this tomorrow.

**Comment by andybalaam** [comment]
Apologies, I am looking at this today.

**Review by andybalaam — APPROVED** [review]
Looks good! Thank you for the contribution.

**Comment by andybalaam** [comment]
Now available in release 1.3.0

**Comment by dhenneke** [comment]
Thanks. I will update my other PR in the react-sdk to consume the new version of the widget-api.

**Pull request merged**
